FROM python:3.11-slim

# Clone pipelines repository
RUN git clone https://github.com/open-webui/pipelines.git

# Change directory
WORKDIR /pipelines

# Install requirements
RUN pip install -r requirements.txt

# Start pipelines
CMD ["./start.sh"]

