version: '3.7'

services:

  ## Ollama 
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  ## Oepen WebUI - front end that supports tika and Ollama
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  ## Apache Tika Server 
  tika:
    container_name: tika
    restart: unless-stopped
    image: apache/tika:latest-full
    ports:
      - "127.0.0.1:9998:9998"
    volumes:
      - ${CONFIG_LOCATION}/tika-config.xml:/tika-config.xml
      - ${STORAGE_LOCATION}/tika:/tika-server/data
    command: ["--config", "/tika-config.xml"]


  # Anything LLM
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
      - "3001:3001"
    volumes:
      - ${STORAGE_LOCATION}/anythingllm:/app/server/storage
      - ${CONFIG_LOCATION}/anythingllm/.env:/app/server/.env
    cap_add:
      - SYS_ADMIN
    environment:
      STORAGE_DIR: /app/server/storage



volumes:
  ollama: {}
  open-webui: {}